name: rain
description: Weather application

publish_to: "none"

version: 1.3.1+34

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.4.2+1
  intl: ^0.18.1
  isar: ^3.1.0+1
  shimmer: ^3.0.0
  iconsax: ^0.0.8
  timezone: ^0.9.2
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  home_widget: ^0.5.0
  workmanager: ^0.5.2
  google_fonts: ^6.2.1
  flutter_glow: ^0.3.0
  url_launcher: ^6.2.5
  time_machine: ^0.9.17
  dynamic_color: ^1.7.0
  path_provider: ^2.1.2
  json_annotation: ^4.8.1
  flutter_timezone: ^1.0.8
  package_info_plus: ^7.0.0
  connectivity_plus: ^6.0.2
  freezed_annotation: ^2.4.1
  isar_flutter_libs: ^3.1.0+1
  flutter_displaymode: ^0.6.0
  lat_lng_to_timezone: ^0.2.0
  flutter_colorpicker: ^1.0.3
  scrollable_positioned_list: ^0.3.8
  flutter_local_notifications: ^17.0.0
  internet_connection_checker_plus: ^2.3.0

# Uncomment this for publishing FLOSS variant
# dependency_overrides:
#   geolocator_android:
#     git:
#       url: https://github.com/Zverik/flutter-geolocator.git
#       ref: floss
#       path: geolocator_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.1
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#181818"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter_native_splash:
  color: "#181818"
  android_12:
    color: "#181818"
  image: "assets/icons/icon.png"

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
